<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sembako extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sembako_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));

        if ($q <> '') {
            $config['base_url'] = base_url() . 'sembako/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'sembako/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'sembako/index';
            $config['first_url'] = base_url() . 'sembako/index';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Sembako_model->total_rows($q);
        $sembako = $this->Sembako_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'title' => 'Detail Harga Sembako',
            'sembako_data' => $sembako,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->display('admin/sembako/sembako_list', $data);
    }


    public function create()
    {
        $data = array(
            'title' => 'Tambah Data Sembako',
            'button' => 'Create',
            'action' => site_url('sembako/create_action'),
            'sembako_id' => set_value('sembako_id'),
            'sembako_nama' => set_value('sembako_nama'),
        );
        $this->template->display('admin/sembako/sembako_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'sembako_nama' => $this->input->post('sembako_nama', TRUE),
            );

            $this->Sembako_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('sembako'));
        }
    }

    public function update($id)
    {
        $row = $this->Sembako_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('sembako/update_action'),
                'sembako_id' => set_value('sembako_id', $row->sembako_id),
                'sembako_nama' => set_value('sembako_nama', $row->sembako_nama),
            );
            $this->template->display('admin/sembako/sembako_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sembako'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('sembako_id', TRUE));
        } else {
            $data = array(
                'sembako_nama' => $this->input->post('sembako_nama', TRUE),
            );

            $this->Sembako_model->update($this->input->post('sembako_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('sembako'));
        }
    }

    public function delete($id)
    {
        $row = $this->Sembako_model->get_by_id($id);

        if ($row) {
            $this->Sembako_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('sembako'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sembako'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('sembako_nama', 'sembako nama', 'trim|required');

        $this->form_validation->set_rules('sembako_id', 'sembako_id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Sembako.php */
/* Location: ./application/controllers/Sembako.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-06 07:34:01 */
/* http://harviacode.com */
